# Generated by Django 5.2.9 on 2026-05-29 07:31

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model("shop", "Category")
    defaults = [
        ("Комнатные растения", "komnatnye-rasteniya"),
        ("Деревья и саженцы", "derevya-i-sazhency"),
        ("Цветы", "cvety"),
    ]
    for name, slug in defaults:
        Category.objects.get_or_create(name=name, defaults={"slug": slug})


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("shop", "Category")
    Category.objects.filter(
        slug__in=["komnatnye-rasteniya", "derevya-i-sazhency", "cvety"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
