# Generated by Django 6.0.5 on 2026-05-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_seed_default_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="care_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easy", "Легкий"),
                    ("medium", "Средний"),
                    ("hard", "Требовательный"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="diameter",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Диаметр в см",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Высота в см",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="light_requirements",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="product",
            name="origin_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="watering",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
