# Generated by Django 6.0.5 on 2026-05-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_product_care_level_product_diameter_product_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=120, verbose_name="Бренд"),
        ),
        migrations.AddField(
            model_name="product",
            name="pot_size",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Размер горшка"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="Артикул"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("in_stock", "В наличии"),
                    ("low_stock", "Мало осталось"),
                    ("preorder", "Под заказ"),
                    ("out_of_stock", "Нет в наличии"),
                ],
                default="in_stock",
                max_length=20,
            ),
        ),
    ]
